adding dai warning for erc20 token vs xdai native token
raid-guild/xdai-omnibridge pull request #83
Opened 2020-09-21 00:53 UTC by brossetti1

in reference [to this discussion](https://discordapp.com/channels/684227450204323876/744945190401474710/757340078354727044)

I opened an [issue here](https://github.com/raid-guild/xdai-omnibridge/issues/82)

I chose not to make this a seperate component because it is just an alert, and its not very complicated. let me know if you need anything to change here, thanks.

2020-09-22 03:27 UTC, dan13ram commented on packages/react-app/src/components/ConfirmTransferModal.jsx
> +  const isERC20Dai = toToken.symbol === 'DAI';
In either cases, should we do a hard-coded address check instead of symbol check?

2020-09-22 03:28 UTC, dan13ram requested changes
Looks great @brossetti1 
Please add this to the responsive mobile screen as well and we can merge this :D

2020-09-22 03:29 UTC, dan13ram commented on packages/react-app/src/components/BridgeTokens.jsx
> +      <Alert status="warning" borderRadius={5} mb={5}>
we can actually move this alert to a separate component and reuse it

2020-09-22 03:30 UTC, dan13ram commented on packages/react-app/src/components/BridgeTokens.jsx
> +          Bridges erc20 Dai to xDai, not the xDai Native token.
Lets wait for xDai team to approve the text as well.

2020-09-23 03:39 UTC, brossetti1 commented
@dan13ram I took another look at this one, split the `DaiWarning` into its own component, and added address checking. One of the scenarios that popped up from that is I had to add logic for which network the user is connected to. since the [content of the message](https://discordapp.com/channels/684227450204323876/744945190401474710/757836994586869760) from the xdai team is:

```
Bridges DAI on Ethereum to DAI on xDai, DOES NOT mint native xDai. If you want native xDai, use the <a href=“https://dai-bridge.poa.network/”>ExDai Bridge</a>.
``` 

I opted to restrict the `<DaiWarning /> to dai fromToken's on ethereum based networks` as the message does not apply going from xdai to dai.

I added the dai address constant in the DaiWarning component as I didn't want to clutter the constants only to store Dai addresses. Let me know what you think or if you want changes here.

### Selection process on large screen:
![Screen Shot 2020-09-22 at 8 03 47 PM](https://user-images.githubusercontent.com/5998100/93964101-0a2f3900-fd1c-11ea-9f90-1fb8ff7fd0b1.png)
![Screen Shot 2020-09-22 at 8 05 12 PM](https://user-images.githubusercontent.com/5998100/93964103-0ac7cf80-fd1c-11ea-8be9-372ad161438f.png)

### Selection process on small screen:
![Screen Shot 2020-09-22 at 8 11 51 PM](https://user-images.githubusercontent.com/5998100/93964106-0b606600-fd1c-11ea-9ebb-4073e277908b.png)
![Screen Shot 2020-09-22 at 8 12 12 PM](https://user-images.githubusercontent.com/5998100/93964107-0bf8fc80-fd1c-11ea-976b-77bf841148ea.png)

2020-09-23 03:41 UTC, brossetti1 commented on packages/react-app/src/components/DaiWarning.jsx
> +}
a little unconventional but I dont see this information being used outside this component.

2020-09-23 03:41 UTC, brossetti1 commented on packages/react-app/src/components/DaiWarning.jsx
> +}
this is also a little unconventional and it is exported, but I only see this being used WITH this component so I put it here.

2020-09-23 03:42 UTC, brossetti1 commented on packages/react-app/src/components/DaiWarning.jsx
> +}
this is also a little unconventional and it is exported, but I only see this being used WITH this component so I put it here.

2020-09-23 03:42 UTC, brossetti1 commented on packages/react-app/src/components/DaiWarning.jsx
> +}
a little unconventional but I dont see this information being used outside this component.

2020-09-23 03:42 UTC, brossetti1 commented on packages/react-app/src/lib/constants.jsx
> +export const ETEHEREUM_NETWORKS = [1, 42];
¯\_(ツ)_/¯

2020-09-23 04:30 UTC, scottrepreneur commented on packages/react-app/src/lib/constants.jsx
> +export const ETEHEREUM_NETWORKS = [1, 42];
got an extra e in ETHEREUM_NETWORKS

2020-09-23 08:59 UTC, dan13ram commented on packages/react-app/src/lib/constants.jsx
> +export const ETEHEREUM_NETWORKS = [1, 42];
Hey instead of creating this new variable there's an existing method called isxDaiChain in `lib/helpers` which helps you do the same thing.

2020-09-23 09:01 UTC, dan13ram commented on packages/react-app/src/components/DaiWarning.jsx
> +            ExDai Bridge
It should be `xDai Bridge` not `ExDai`.
Also you don't need to set `rel="..."` when you are setting isExternal.

2020-09-23 09:06 UTC, dan13ram commented on packages/react-app/src/components/BridgeTokens.jsx
> +  AlertIcon,
This is causing lint errors, please remove it. Else it won't build.

2020-09-23 09:07 UTC, dan13ram commented on packages/react-app/src/components/DaiWarning.jsx
> +        <AlertIcon />
Can you set a minW for this icon, it becomes too small for smaller screens

2020-09-23 09:09 UTC, dan13ram requested changes
Great stuff man! Just some small changes before we can merge it :)

2020-09-23 14:04 UTC, brossetti1 commented
@dan13ram nice catch, fixed the remaining feedback. heres a shot of the small screen alert icon

<img width="464" alt="Screen Shot 2020-09-23 at 8 03 20 AM" src="https://user-images.githubusercontent.com/5998100/94023412-68d3d180-fd73-11ea-9d56-884f8d4c7239.png">

2020-09-23 14:17 UTC, dan13ram approved these changes

2020-09-23 15:10 UTC, scottrepreneur approved these changes
great work

2020-09-23 15:15 UTC, merged